type TarotCard = {
  name: string;
  symbol: string;
  energy: string;
  colour: string;
  colourHex: string;
  message: string;
  archetype: string;
};

export type { TarotCard };
export const TAROT_CARDS: TarotCard[] = [
  {
    name: "The Fool",
    symbol: "☽",
    energy: "Fearless spontaneity — dress like no one is watching.",
    colour: "Sunshine Yellow",
    colourHex: "#F9D94E",
    message: "Today is for bold experiments. Wear something you've been too nervous to try. The universe rewards audacity.",
    archetype: "The Free Spirit",
  },
  {
    name: "The Magician",
    symbol: "✦",
    energy: "Magnetic confidence — you are the main character today.",
    colour: "Crimson Red",
    colourHex: "#C0392B",
    message: "Every piece in your wardrobe is a tool. Today you wield them masterfully. Dress with intention and watch the world respond.",
    archetype: "The Powerhouse",
  },
  {
    name: "The High Priestess",
    symbol: "◈",
    energy: "Quiet mystery — let your style speak in whispers.",
    colour: "Midnight Blue",
    colourHex: "#1A237E",
    message: "Less is more today. Choose one statement piece and let everything else recede. Your presence does the talking.",
    archetype: "The Minimalist",
  },
  {
    name: "The Empress",
    symbol: "❋",
    energy: "Lush abundance — wrap yourself in comfort and beauty.",
    colour: "Sage Green",
    colourHex: "#7D9B6A",
    message: "Lean into texture and softness today. Flowing fabrics, natural tones, something that feels as good as it looks.",
    archetype: "The Romantic",
  },
  {
    name: "The Emperor",
    symbol: "▲",
    energy: "Structured authority — sharp lines command the room.",
    colour: "Charcoal",
    colourHex: "#3D3D3D",
    message: "Today calls for your most tailored pieces. Structure signals strength. A well-fitted blazer changes everything.",
    archetype: "The Executive",
  },
  {
    name: "The Hierophant",
    symbol: "⊕",
    energy: "Timeless tradition — classics never fail.",
    colour: "Ivory",
    colourHex: "#F5F0E8",
    message: "Return to your wardrobe staples today. That piece you always reach for? It's perfect. Trust what has always worked.",
    archetype: "The Classic",
  },
  {
    name: "The Lovers",
    symbol: "♡",
    energy: "Harmonious pairing — everything works together today.",
    colour: "Dusty Rose",
    colourHex: "#C9917A",
    message: "Focus on the perfect combination. Two pieces you've never paired before might be your best outfit yet. Trust the match.",
    archetype: "The Curator",
  },
  {
    name: "The Chariot",
    symbol: "→",
    energy: "Driven momentum — dress for where you're going, not where you are.",
    colour: "Electric Blue",
    colourHex: "#1565C0",
    message: "Wear your most purposeful outfit today. The kind that makes you walk faster and stand taller. You have places to be.",
    archetype: "The Achiever",
  },
  {
    name: "Strength",
    symbol: "∞",
    energy: "Graceful power — soft on the outside, fierce within.",
    colour: "Warm Terracotta",
    colourHex: "#C1654A",
    message: "Choose pieces that feel like armour but look effortless. True style strength is never loud — it just is.",
    archetype: "The Warrior",
  },
  {
    name: "The Hermit",
    symbol: "◎",
    energy: "Intentional solitude — dress purely for yourself today.",
    colour: "Stone Grey",
    colourHex: "#8D8D8D",
    message: "Strip everything back. Wear only what genuinely makes you feel like you. No performance, no audience. Just you.",
    archetype: "The Purist",
  },
  {
    name: "Wheel of Fortune",
    symbol: "◉",
    energy: "Lucky spontaneity — let fate pick your outfit.",
    colour: "Gold",
    colourHex: "#D4A017",
    message: "Reach into your wardrobe without looking and pull something out. Wear it. Fortune favours the bold and the random.",
    archetype: "The Adventurer",
  },
  {
    name: "Justice",
    symbol: "⚖",
    energy: "Balanced precision — every detail considered.",
    colour: "Deep Teal",
    colourHex: "#00695C",
    message: "Edit ruthlessly today. If anything feels slightly off, change it. You deserve an outfit that is exactly right.",
    archetype: "The Perfectionist",
  },
  {
    name: "The Hanged One",
    symbol: "⌁",
    energy: "Suspended curiosity — see your wardrobe upside down.",
    colour: "Lavender",
    colourHex: "#9575CD",
    message: "Wear something in a completely unexpected way today. A dress as a top, a belt as a necklace. Shift the perspective.",
    archetype: "The Subversive",
  },
  {
    name: "Death",
    symbol: "◇",
    energy: "Transformative release — let go of what no longer fits.",
    colour: "Jet Black",
    colourHex: "#1A1A1A",
    message: "Today is for reinvention. Wear all black and let it be a ceremony. Something old ends, something new begins.",
    archetype: "The Transformer",
  },
  {
    name: "Temperance",
    symbol: "≈",
    energy: "Effortless balance — mix high and low, old and new.",
    colour: "Soft Blush",
    colourHex: "#E8B4A0",
    message: "The magic is in the mix today. Pair your most elevated piece with something casual. Contrast is the whole point.",
    archetype: "The Blender",
  },
  {
    name: "The Devil",
    symbol: "✧",
    energy: "Unapologetic edge — lean into your dark side.",
    colour: "Deep Burgundy",
    colourHex: "#6D1B2E",
    message: "Wear the thing that feels a little dangerous. The piece that turns heads. Own it completely. No apologies today.",
    archetype: "The Provocateur",
  },
  {
    name: "The Tower",
    symbol: "⌇",
    energy: "Radical disruption — break every style rule you know.",
    colour: "Bright Orange",
    colourHex: "#E65100",
    message: "Throw out your comfort zone entirely. The outfit that makes you pause before leaving the house? That's the one.",
    archetype: "The Rule Breaker",
  },
  {
    name: "The Star",
    symbol: "★",
    energy: "Luminous hope — shine without trying.",
    colour: "Celestial Silver",
    colourHex: "#B0BEC5",
    message: "Wear something that reflects light today — literally or figuratively. You are allowed to take up space and shimmer.",
    archetype: "The Dreamer",
  },
  {
    name: "The Moon",
    symbol: "☾",
    energy: "Intuitive dressing — let your gut choose everything.",
    colour: "Pearl White",
    colourHex: "#F0EDE8",
    message: "Don't overthink a single piece today. The first thing you reach for is exactly right. Trust your instincts completely.",
    archetype: "The Intuitive",
  },
  {
    name: "The Sun",
    symbol: "☀",
    energy: "Radiant joy — dress like today is a celebration.",
    colour: "Warm Amber",
    colourHex: "#F59E0B",
    message: "Wear your most joyful outfit. The one that makes you smile when you put it on. Today deserves your brightest self.",
    archetype: "The Optimist",
  },
  {
    name: "Judgement",
    symbol: "♪",
    energy: "Bold awakening — step into your next style era.",
    colour: "Royal Purple",
    colourHex: "#6A1B9A",
    message: "You are not who you were last season. Dress for the version of yourself you are becoming, not who you've been.",
    archetype: "The Evolved",
  },
  {
    name: "The World",
    symbol: "⊙",
    energy: "Complete mastery — today you can wear absolutely anything.",
    colour: "Emerald Green",
    colourHex: "#1B5E20",
    message: "You have arrived. Every piece you own is an option today. There are no wrong choices — only your choices.",
    archetype: "The Master",
  },
];